### PR TITLE
PLANNER-579 Reduce WARN messages during startup

### PR DESCRIPTION
**Pull request by mcimbora**
Fixes warnings when starting OptaPlanner WB in Super Dev Mode

WARN  [org.jboss.weld.Event] WELD-000411: Observer method [BackedAnnotatedMethod] org.kie.internal.runtime.cdi.ActivateExtension.processAnnotatedType(@Observes ProcessAnnotatedType<Object>, BeanManager) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.

### CODE REVIEW

**Comment by mrietveld** [comment]
@ge0ffrey Could you take a quick look and +1/-1 this? Thanks!

**Comment by mrietveld** [comment]
( https://github.com/droolsjbpm/droolsjbpm-knowledge/pull/147/files?w=1 will show the actual changes.. )

**Comment by ge0ffrey** [comment]
+1 Looks ok for me

**Comment by psiroky** [comment]
Merged by https://github.com/droolsjbpm/droolsjbpm-knowledge/commit/f5a293e34b754b9aa06bbf7b3e5a6b7cb2743207

**Pull request closed without merging**
