### PR TITLE
DROOLS-914 - introduce revapi maven plugin to check backward compatib…

### PR DESCRIPTION
**Pull request by rsynek**
…ility

### CODE REVIEW

**Comment by psiroky** [comment]
It seems the revapi plugin requires Java 8 (or at least was built to support only Java 8+). This is unfortunately blocker for us as we are using currently JDK 7 to build our repos (and there are no short-therm plans to change that).

The only way I see is to put it into separate profile (not ideal though as we trying to keep the number of different profiles at minimum). But then it would not be run for default builds, which partially defeats the purpose (but we can still have separate Jenkins job to run just this analysis on JDK8).

When running with JDK7 +Maven 3.2.3 I am getting:
`Caused by: java.lang.UnsupportedClassVersionError: org/revapi/maven/CheckMojo : Unsupported major.minor version 52.0`

**Comment by rsynek** [comment]
Revapi will be ported to JDK 7 in short future. As soon as this happens, I will update plugin version to the new release.

**Comment by psiroky** [comment]
Merged into master and 6.3.x. I configured the plugin to check compatibility to 6.2.0.Final. There is a quite a few failures there. Mostly added methods to interfaces and changed return types. We should look at those and least confirm that these are expected.

I will also setup Jenkins job which will runs these checks periodically.

**Comment by psiroky** [comment]
Thanks @rsynek!

**Comment by mrietveld** [comment]
Thanks @psiroky  and @rsynek !

**Pull request closed without merging**
