### PR TITLE
JBPM-4625 Generation of JPA enabled models

### PR DESCRIPTION
**Pull request by wmedvede**
persistence.xml descriptor processing, basically marshall/unmarshal  xml <-> model

### CODE REVIEW

**Comment by manstis** [comment]
@wmedvede Hi Walter, can you explain why these classes are in ```droolsjbpm-knowledge``` (I'm not saying they should not be, but since they're used by the WB I'd have thought kie-wb-common was more appropriate - given my limited knowledge of this change). Also, should the ```Serializable``` classes also have a ```serialVersionUID```?

**Comment by manstis** [comment]
@wmedvede I know it's your choice, but why do you have these classes and similar in ```kie-wb-common``` and then (un)marshall between the two sets of classes? Would one set of classes be easier to maintain - and change the XML<->Objects marshalling to use another XML parser (e.g. SAX/StAX) instead of JAXB?

**Comment by wmedvede** [comment]
I asked this query to my self too. I think this classes are now only used by the workbench, but I'm 90% sure that in the future they will be also used by the jbpm deployment services o even by the unifided execution server. At some point when a project with persistence is about to be deployed, we should excecute code that will create the EntityManagerFactory for the given project, etc. I don't know where this  code will be at this moment. 

Assuming that the PersisteneDescirptor will be used at some poing by core components (as I believe) then it's not bad to have the Portable representation of the descriptor. In this way the core stuff is maintained separate from the Portable stuff, etc.

**Comment by mswiderski** [comment]
Walter, Mike, I don't think we are going to use these classes on runtime when deploying and bootstrapping the persistence for given project. jBPM itself does delegate the read of persistence.xml (and to interpret it) to JPA provider (in our case hibernate). jBPM does not really care what's inside the persistence.xml and expect to get EntityManagerFactory when invoking Persistence.createEntityManagerFactory. Nothing else. So the main requirement is to ensure that persistence.xml is in expected location (META-INF/persistence.xml) so JPA provider can find it.

**Comment by wmedvede** [comment]
I guess that likely the runtime don't really care at this moment, cause you are doing a kind of Standalone deployment relaying all the deployment to the Persistence.createEntityManager(XXX). But as soon as we wants to do something more controlled, like pre-check if the data base already has a schema with tables inside (and send an alert to the user), etc., then we will need it. 
e.g. when the module is about to be deployed in UI mode, we can rise an alert to the user saying "hej, the database already contains data, do you still want to deploy"

I'm not sure if we should provide a mechanism that do the persistence deployment only for jBPM projects.  
Sooner or later I guess we will need something more elaborated, for example, a platform service that can do the formal instanciation of the EntityManagerFactories. And likely keep an internal registry with the registered persistence units, etc. Having this, modules like the dashbuilder that wants to do JPA queries query on a given persistence unit can consume this service too.
Another example is probably the FormModeller, for example, if we have an entity Currency, when a form is about to be painted, and we want to show a dropdown with all the available currencies, likely the form runtime will need to get access to the EntiyManager in order to populate the dropdown with the values from DB.

**Comment by wmedvede** [comment]
To not enter in a never ending discussion I've sent part of previous work to the transh, and moved everithing to kie-wb-commons

**Pull request closed without merging**
