### PR TITLE
DROOLS-1035 + remove Activator + various small clean-ups

### PR DESCRIPTION
**Pull request by psiroky**
I originally meant to only fix the overview.html (DROOLS-1035), but end-up touching many more classes and fixing other things as well (thus multiple commits as most of them deal with different things. It should also make it easier to review).

Most notable changes:
 * class `org.kie.api.osgi.Activator` was removed as I could not find any place using, nor a good reason to keep it. Please speak-up if you know a valid reason for this class to stay.

 * fixed few small compiler warnings

 * fixed ~150 Javadoc warnings (mostly empty @return tags)

There are other things to fix, but I want to do this in smaller chunks so that it can reviewed more easily.

https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/147 needs to be merged before/together with this one.

@mariofusco, @etirelli, @mrietveld, @mswiderski  any comments more than welcome. Thanks!

### CODE REVIEW

**Comment by mrietveld** [comment]
I don't know enough about OSGi, but I think the Activator class was neccessary for OSGi integration. 

+1 for everything _except_ for the Activator class change.

**Comment by mariofusco** [comment]
+1 including Activator removal. It's commented out in the pom so it is evident that it is no longer in use.

**Comment by psiroky** [comment]
Rebased and fixed merge conflicts.

**Comment by psiroky** [comment]
I am holding on the merge for now. @mdproctor would like to review as well (especially the Activator removal).

**Comment by psiroky** [comment]
Rebased on top of the latest master. @mdproctor did you have a chance to look at this?

**Pull request merged**
