### PR TITLE
kie-api: move the revapi-check into default build

### PR DESCRIPTION
**Pull request by psiroky**
* no need for the profile anymore as Java 8+ is
   now required for the repo to build

### CODE REVIEW

**Comment by psiroky** [comment]
@mrietveld or @mariofusco could you please take a look?

**Comment by mrietveld** [comment]
+1 Thanks, Petr!

Could you make sure to add the same thing to the 6.4.x branch?

**Comment by psiroky** [comment]
Unfortunately, we can't apply this to 6.4.x. We still need to support JDK 7 there the build and the revapi-check needs Java 8.

**Comment by mrietveld** [comment]
@psiroky Ah, of course. Thanks.

**Pull request merged**
