### PR TITLE
DROOLS-912 - adding the ability to create the audit log from the Command API

### PR DESCRIPTION
**Pull request by reynoldsm88**
Made necessary changes to the Command Factory to support this feature, there is a another PR for drools-core: https://github.com/droolsjbpm/drools/pull/497

### CODE REVIEW

**Comment by mrietveld** [comment]
By default, only features that have been around for a while are added to interfaces in the `kie-api`module. As a project, we have to make sure that any changes made to our public API (`kie-api`) are ones we fully support and are planning on supporting for a long time. 

Would you mind moving this code to the `kie-internal` module?

**Comment by reynoldsm88** [comment]
Sure no problem.

**Comment by reynoldsm88** [comment]
After reviewing the project structure I have some concerns about moving this code entirely into kie-internal. CommandFactory uses a provider to create commands, and the provider is an interface defined in kie-api, the implementation is in drools-core. CommandFactory itself is in kie-internal, however, the commands themselves are implemented in drools-core. Therefore, to add the new command by directly creating in in CommandFactory without the provider would be a very jarring break in the pattern in how commands are implemented.

**Comment by mrietveld** [comment]
@reynoldsm88 We're unwilling to add these changes to `kie-api`. I have just discussed this with @mariofusco and he agrees that we do not want these changes in `kie-api` yet. 

Is it possible to maybe add a new interface to `kie-internal` that the interface in `kie-api` would then extend? Or another creative solution to this that would keep the methods from being exposed in `kie-api`? 

Thanks.

**Comment by reynoldsm88** [comment]
Sure let me see what I can do tonite.

**Comment by reynoldsm88** [comment]
I've updated the code here, there is a related update here that should probably be reviewed at the same time

https://github.com/droolsjbpm/drools/pull/497

**Comment by mrietveld** [comment]
Thanks!

**Comment by mrietveld** [comment]
@mariofusco If you get a chance to approve this, I can merge it.

**Comment by mariofusco** [comment]
@mrietveld That's ok for me. Feel free to merge this PR and the corresponding one in drools.

**Comment by reynoldsm88** [comment]
@mrietveld did you get a chance to review the drools one as well? If you are okay with that then I think this issue is settled, right?

**Comment by mrietveld** [comment]
Merged @ https://github.com/droolsjbpm/droolsjbpm-knowledge/commit/40da0a785374cff27e445cc050782fc4d1afd0a1

**Comment by reynoldsm88** [comment]
Thanks so much!!!

**Pull request closed without merging**
