### PR TITLE
BZ-1125077 - Limiting serialization classes in a deployment

### PR DESCRIPTION
**Pull request by mrietveld**
Depends on: 

Depended on by:

- https://github.com/droolsjbpm/jbpm/pull/356
- https://github.com/droolsjbpm/droolsjbpm-integration/pull/248
- https://github.com/droolsjbpm/kie-docs/pull/22

### CODE REVIEW

**Comment by mrietveld** [comment]
@mswiderski Would you mind looking at this?

**Comment by mrietveld** [comment]
Some more info (although it may be confusing?): https://github.com/mrietveld/jbpm/wiki/Limit-Deployment-Serialization-Classes

**Comment by mswiderski** [comment]
looking good

the idea is to have this configurable per project level right? And that's why it's added into deployment descriptor... initially I though it will be global switch but with deployment descriptor it does provide lots of flexibility

If we stick to change in deployment descriptor then we have to add support for it in deployment descriptor editor in workbench so people can simply set it. I'd add it as well to default (Server level) descriptor for completeness that is shipped with workbench too:
https://github.com/droolsjbpm/kie-wb-distributions/blob/master/kie-wb/kie-wb-webapp/src/main/resources/META-INF/kie-wb-deployment-descriptor.xml

**Comment by mswiderski** [comment]
+1 with these small needs to update deployment descriptor editor and default descriptor used in workbench

**Comment by mrietveld** [comment]
@mswiderski Where is the code for the descriptor modification in the workbench located?

**Comment by mrietveld** [comment]
@mswiderski Do you just want me to add `<limit-serializationclasses>true<limit-serializationclasses>/>` to the kie-wb-deployment-descriptor.xml file?

**Comment by mswiderski** [comment]
here is the code for deployment descriptor editor:
https://github.com/droolsjbpm/jbpm-console-ng/tree/master/jbpm-console-ng-workbench-integration

regarding adding to deployment descriptor.xml - yes, please

**Comment by mrietveld** [comment]
deployment descriptor.xml PR: https://github.com/droolsjbpm/kie-wb-distributions/pull/160

**Comment by mrietveld** [comment]
Working on console fix.

**Comment by mrietveld** [comment]
@mswiderski Thanks for merging. 

Descriptor editor PR: https://github.com/droolsjbpm/jbpm-console-ng/pull/237/files

**Pull request closed without merging**
