### PR TITLE
JBPM-4812 - Allow to query by task variables

### PR DESCRIPTION
**Pull request by mrietveld**
Depends on: 
- (nothing)

Needed by: 
- https://github.com/droolsjbpm/jbpm/pull/325
- https://github.com/droolsjbpm/droolsjbpm-integration/pull/221

### CODE REVIEW

**Comment by mrietveld** [comment]
@mswiderski Please check.

**Comment by mswiderski** [comment]
so this includes both commits which kind of replaces the initial commit, if that's the case I'll take this and use locally for running the tests. thanks @mrietveld

**Comment by mrietveld** [comment]
@mswiderski Yes, this should replace your PR: it includes your initial commit plus my commit on top of it which moves from the "normal" methods to fluent query methods.

**Comment by mswiderski** [comment]
closing as new PR including all changes will be submitted

**Pull request closed without merging**
